name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ main ]

jobs:
  history-cleanliness:
    uses: ./.github/workflows/history-cleanliness.yml
    secrets: inherit

  test:
    needs: history-cleanliness
    uses: ./.github/workflows/test.yml
    secrets: inherit

  lint:
    needs: history-cleanliness
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  integration:
    needs: [test, lint]
    uses: ./.github/workflows/integration.yml
    secrets: inherit
