name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  history-cleanliness:
    uses: ./.github/workflows/history-cleanliness.yml

  test:
    needs: history-cleanliness
    uses: ./.github/workflows/test.yml
    secrets: inherit

  lint:
    needs: history-cleanliness
    uses: ./.github/workflows/lint.yml

  integration:
    needs: [test, lint]
    uses: ./.github/workflows/integration.yml
