name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Run tests
      run: go test -v ./... -coverprofile=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.out

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

  integration:
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Run integration tests
      run: go test -tags=integration -parallel 6 -timeout=20m -v ./integration/...
