name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Go tools
        run: |
          go install golang.org/x/tools/gopls@latest
          go install github.com/go-delve/delve/cmd/dlv@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest

      - name: Download modules
        run: go mod download

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: uv tool install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks
