name: Integration

on:
  workflow_call:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: go.sum

    - name: Ensure worker image available
      run: docker pull alpine:latest

    - name: Run integration tests
      run: go test -tags=integration -parallel 6 -timeout=20m -v ./integration/...
